apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
      initContainers:
        - name: init
          image: busybox
          command: ['sh', '-c', 'echo "<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #f0f0f0;
            font-family: Arial, sans-serif;
        }
        .centered {
            text-align: center;
        }
        h1 {
            color: #333;
        }
    </style>
</head>
<body>
    <div class="centered">
        <h1>Helloo les DevOps, Challenge OK!!</h1>
    </div>
    <div style="width:100%;height:0;padding-bottom:100%;position:relative;"><iframe src="https://giphy.com/embed/j4kb8qhLpnIc2vXcdC" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/canalplus-laflamme-flambeau-leflambeau-j4kb8qhLpnIc2vXcdC">via GIPHY</a></p>
</body>
</html>" > /usr/share/nginx/html/index.html']
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: volume
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: volume
