replicaCount: 1
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.20.1-alpine"
service:
  type: LoadBalancer
  port: 80
pvc:
  accessModes:
    - ReadWriteOnce
  storageClassName: s3-standard
  resources:
    requests:
      storage: 1Gi
cronjob:
  schedule: "0 * * * *"
  jobImage:
    repository: "busybox"
    tag: "1.28"
    pullPolicy: IfNotPresent
  command: ['date']